/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/layouts/Default/Main/Header/Breadcrumb.vue')['default']
    Default: typeof import('./../src/components/layouts/Default/index.vue')['default']
    ECharts: typeof import('./../src/components/shared/ECharts.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FragmentList: typeof import('./../src/components/shared/fragments/FragmentList.vue')['default']
    Header: typeof import('./../src/components/layouts/Default/Header/index.vue')['default']
    Humburger: typeof import('./../src/components/layouts/Default/Main/Header/Humburger.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpView: typeof import('~icons/ep/view')['default']
    ISvgFileCopy: typeof import('~icons/svg/file-copy')['default']
    ISvgVue: typeof import('~icons/svg/vue')['default']
    LayoutDefault: typeof import('./../src/components/layouts/LayoutDefault/index.vue')['default']
    LayoutHeader: typeof import('./../src/components/layouts/Default/LayoutHeader.vue')['default']
    LeftSide: typeof import('./../src/components/layouts/Default/LeftSide/index.vue')['default']
    Main: typeof import('./../src/components/layouts/Default/Main/index.vue')['default']
    NavMenu: typeof import('./../src/components/layouts/Default/LeftSide/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsView: typeof import('./../src/components/layouts/Default/Main/Header/TagsView.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
