/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/layouts/Header/Breadcrumb.vue')['default']
    Default: typeof import('./../src/components/layouts/Default.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FadeRouteAnimation: typeof import('./../src/components/animations/routerViews/FadeRouteAnimation.vue')['default']
    FadeRouterView: typeof import('./../src/components/animations/routerViews/FadeRouterView.vue')['default']
    FragmentList: typeof import('./../src/components/shared/fragments/FragmentList.vue')['default']
    Header: typeof import('./../src/components/layouts/Header/index.vue')['default']
    Humburger: typeof import('./../src/components/layouts/Header/Humburger.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    ISvgFileCopy: typeof import('~icons/svg/file-copy')['default']
    ISvgVue: typeof import('~icons/svg/vue')['default']
    NavMenu: typeof import('./../src/components/layouts/NavMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsView: typeof import('./../src/components/layouts/Header/TagsView.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
